rewrite

diff --git a/qt-pending-translation/action.yml b/qt-pending-translation/action.yml
--- a/qt-pending-translation/action.yml
+++ b/qt-pending-translation/action.yml
@@ -18,30 +18,17 @@ runs:
           shell: bash
 
         - run: |
-            for filename in $(grep -o [A-Za-z_/]*.ts ${{ inputs.pro-file }}) ;
-            do
-                echo "Checking $filename"
-                cp $filename ${filename}_bak                
-                /opt/hostedtoolcache/Python/${{ inputs.python-version }}/x64/bin/pylupdate5 -verbose -noobsolete ./${{ inputs.pro-file }}
-
-                echo "Comparing files - exit code 1 if new strings exists"
-                cmp -b $filename ${filename}_bak
-                if cmp -s $filename ${filename}_bak ; then
-                    echo "Everything fine"
-
-                    echo "Removing ${filename}_bak"
-                    rm ${filename}_bak
-                else
-                    echo "New translations"
-
-                    echo "Removing ${filename}_bak"
-                    rm ${filename}_bak
-
-                    echo "::error ::There are new strings waiting for translation."
-                    exit 1  
-                fi
-                echo ""
-            done
+            /opt/hostedtoolcache/Python/${{ inputs.python-version }}/x64/bin/pylupdate5 -verbose -noobsolete ./${{ inputs.pro-file }} 2>&1 | tee comparison.txt
+            content=$(cat comparison.txt)
+            if [[ content = *"0 new"*]];
+            then
+                echo "Everything fine"
+            else
+                echo "New translations"
+                echo "::error ::There are new strings waiting for translation."
+                exit 1 
+            fi                     
+            echo ""
           shell: bash
 
         - run: |
